services:
  mysql:
    image: mysql:8.0
    container_name: mysql_nest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_api_atividades
      MYSQL_USER: nest
      MYSQL_PASSWORD: nest123
    ports:
      - "3306:3306"
    volumes:
      - /var/lib/mysql
